// Code generated by Kitex v0.9.1. DO NOT EDIT.

package botservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	bot "github.com/jizizr/LanMei/server/rpc_gen/kitex_gen/bot"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetMessage": kitex.NewMethodInfo(
		getMessageHandler,
		newBotServiceGetMessageArgs,
		newBotServiceGetMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	botServiceServiceInfo                = NewServiceInfo()
	botServiceServiceInfoForClient       = NewServiceInfoForClient()
	botServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return botServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return botServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return botServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "BotService"
	handlerType := (*bot.BotService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "bot",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func getMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*bot.BotServiceGetMessageArgs)
	realResult := result.(*bot.BotServiceGetMessageResult)
	success, err := handler.(bot.BotService).GetMessage(ctx, realArg.Message)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBotServiceGetMessageArgs() interface{} {
	return bot.NewBotServiceGetMessageArgs()
}

func newBotServiceGetMessageResult() interface{} {
	return bot.NewBotServiceGetMessageResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetMessage(ctx context.Context, message *bot.Message) (r *bot.Response, err error) {
	var _args bot.BotServiceGetMessageArgs
	_args.Message = message
	var _result bot.BotServiceGetMessageResult
	if err = p.c.Call(ctx, "GetMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
