// Code generated by Kitex v0.9.1. DO NOT EDIT.

package rpcservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	bot "github.com/jizizr/LanMei/server/rpc_gen/kitex_gen/bot"
	rpc "github.com/jizizr/LanMei/server/rpc_gen/kitex_gen/rpc"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Call(ctx context.Context, message *bot.Message, callOptions ...callopt.Option) (r bool, err error)
	Type(ctx context.Context, empty *rpc.Empty, callOptions ...callopt.Option) (r rpc.CmdType, err error)
	Command(ctx context.Context, empty *rpc.Empty, callOptions ...callopt.Option) (r *rpc.Cmd, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kRpcServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRpcServiceClient struct {
	*kClient
}

func (p *kRpcServiceClient) Call(ctx context.Context, message *bot.Message, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Call(ctx, message)
}

func (p *kRpcServiceClient) Type(ctx context.Context, empty *rpc.Empty, callOptions ...callopt.Option) (r rpc.CmdType, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Type(ctx, empty)
}

func (p *kRpcServiceClient) Command(ctx context.Context, empty *rpc.Empty, callOptions ...callopt.Option) (r *rpc.Cmd, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Command(ctx, empty)
}
