// Code generated by Kitex v0.9.1. DO NOT EDIT.

package rpcservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	bot "github.com/jizizr/LanMei/server/rpc_gen/kitex_gen/bot"
	rpc "github.com/jizizr/LanMei/server/rpc_gen/kitex_gen/rpc"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Call": kitex.NewMethodInfo(
		callHandler,
		newRpcServiceCallArgs,
		newRpcServiceCallResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Type": kitex.NewMethodInfo(
		typeHandler,
		newRpcServiceTypeArgs,
		newRpcServiceTypeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Command": kitex.NewMethodInfo(
		commandHandler,
		newRpcServiceCommandArgs,
		newRpcServiceCommandResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	rpcServiceServiceInfo                = NewServiceInfo()
	rpcServiceServiceInfoForClient       = NewServiceInfoForClient()
	rpcServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return rpcServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return rpcServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return rpcServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RpcService"
	handlerType := (*rpc.RpcService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "rpc",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func callHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rpc.RpcServiceCallArgs)
	realResult := result.(*rpc.RpcServiceCallResult)
	success, err := handler.(rpc.RpcService).Call(ctx, realArg.Message)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newRpcServiceCallArgs() interface{} {
	return rpc.NewRpcServiceCallArgs()
}

func newRpcServiceCallResult() interface{} {
	return rpc.NewRpcServiceCallResult()
}

func typeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rpc.RpcServiceTypeArgs)
	realResult := result.(*rpc.RpcServiceTypeResult)
	success, err := handler.(rpc.RpcService).Type(ctx, realArg.Empty)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newRpcServiceTypeArgs() interface{} {
	return rpc.NewRpcServiceTypeArgs()
}

func newRpcServiceTypeResult() interface{} {
	return rpc.NewRpcServiceTypeResult()
}

func commandHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rpc.RpcServiceCommandArgs)
	realResult := result.(*rpc.RpcServiceCommandResult)
	success, err := handler.(rpc.RpcService).Command(ctx, realArg.Empty)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRpcServiceCommandArgs() interface{} {
	return rpc.NewRpcServiceCommandArgs()
}

func newRpcServiceCommandResult() interface{} {
	return rpc.NewRpcServiceCommandResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Call(ctx context.Context, message *bot.Message) (r bool, err error) {
	var _args rpc.RpcServiceCallArgs
	_args.Message = message
	var _result rpc.RpcServiceCallResult
	if err = p.c.Call(ctx, "Call", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Type(ctx context.Context, empty *rpc.Empty) (r rpc.CmdType, err error) {
	var _args rpc.RpcServiceTypeArgs
	_args.Empty = empty
	var _result rpc.RpcServiceTypeResult
	if err = p.c.Call(ctx, "Type", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Command(ctx context.Context, empty *rpc.Empty) (r *rpc.Cmd, err error) {
	var _args rpc.RpcServiceCommandArgs
	_args.Empty = empty
	var _result rpc.RpcServiceCommandResult
	if err = p.c.Call(ctx, "Command", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
