// Code generated by Kitex v0.9.1. DO NOT EDIT.
package rpcservice

import (
	server "github.com/cloudwego/kitex/server"
	rpc "github.com/jizizr/LanMei/server/rpc_gen/kitex_gen/rpc"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler rpc.RpcService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler rpc.RpcService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
