// Code generated by hertz generator.

package bot

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	//return []app.HandlerFunc{
	//	mw.SigAuth(),
	//}
	return nil
}

func _getmessageMw() []app.HandlerFunc {
	// your code...
	return nil
}
