// Code generated by Kitex v0.9.1. DO NOT EDIT.

package rpcservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	bot "github.com/jizizr/LanMei/server/rpc_gen/kitex_gen/bot"
	hitokoto "github.com/jizizr/LanMei/server/rpc_gen/kitex_gen/hitokoto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Call": kitex.NewMethodInfo(
		callHandler,
		newRpcServiceCallArgs,
		newRpcServiceCallResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	rpcServiceServiceInfo                = NewServiceInfo()
	rpcServiceServiceInfoForClient       = NewServiceInfoForClient()
	rpcServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return rpcServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return rpcServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return rpcServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RpcService"
	handlerType := (*hitokoto.RpcService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "hitokoto",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func callHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*hitokoto.RpcServiceCallArgs)
	realResult := result.(*hitokoto.RpcServiceCallResult)
	success, err := handler.(hitokoto.RpcService).Call(ctx, realArg.Message)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newRpcServiceCallArgs() interface{} {
	return hitokoto.NewRpcServiceCallArgs()
}

func newRpcServiceCallResult() interface{} {
	return hitokoto.NewRpcServiceCallResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Call(ctx context.Context, message *bot.Message) (r bool, err error) {
	var _args hitokoto.RpcServiceCallArgs
	_args.Message = message
	var _result hitokoto.RpcServiceCallResult
	if err = p.c.Call(ctx, "Call", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
